export const CREATE_TASK = 'CREATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';

export const ADD_OPERATION_LOG = 'ADD_OPERATION_LOG';
export const DELETE_ALL_OPERATION_LOG = 'DELETE_ALL_OPERATION_LOG';