export const CREATE_TASK = 'CREATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';

export const DIALOG_OPNE = 'DIALOG_OPNE';
export const DIALOG_AGREEMENT = 'DIALOG_AGREEMENT';
export const DIALOG_DISAGREEMENT = 'DIALOG_DISAGREEMENT';

export const ADD_OPERATION_LOG = 'ADD_OPERATION_LOG';
export const DELETE_OPERATION_LOG = 'DELETE_OPERATION_LOG';
export const DELETE_ALL_OPERATION_LOG = 'DELETE_ALL_OPERATION_LOG';